### ISSUE TITLE
Problem adding NPC vehicle into the simulation

### ISSUE THREAD

**Issue by AlamHasabie** [OSSDC/OSSDC-SIM#10]
Hi,

I'm trying to migrate from LGSVL to OSSDC. A quick run of this quickstart script (`08-create-npc.py`) produces the following error : 
`Python API Quickstart #8: Creating various NPCs
Traceback (most recent call last):
  File "08-create-npc.py", line 38, in <module>
    sim.add_agent(name, lgsvl.AgentType.NPC, state)
  File "/Users/nurhasabie/Documents/lgsvl-venv/lib/python3.8/site-packages/lgsvl-2021.1-py3.8.egg/lgsvl/utils.py", line 23, in new_f
  File "/Users/nurhasabie/Documents/lgsvl-venv/lib/python3.8/site-packages/lgsvl-2021.1-py3.8.egg/lgsvl/simulator.py", line 164, in add_agent
  File "/Users/nurhasabie/Documents/lgsvl-venv/lib/python3.8/site-packages/lgsvl-2021.1-py3.8.egg/lgsvl/remote.py", line 69, in command
Exception: Object reference not set to an instance of an object`

It seems to be related to this issue : https://github.com/lgsvl/simulator/issues/1336 .I've tried to add the missing NPCs and Pedestrians folder into both the AssetBundles and 2021.3-ossdc sim, but the issue does not resolve. Does anyone know how to resolve the problem ? Thanks !

**Comment by mslavescu** [comment]
I update the zip files with extra assets, download them again and the scenario above should work:
https://github.com/OSSDC/OSSDC-SIM/releases/tag/OSSDC-SIM-v1.1

Here is a screenshots with the NPC after running "08-create-npc.py":
![Screenshot 2022-09-07 183139](https://user-images.githubusercontent.com/461669/188995579-c3e4271b-a024-45f8-ab09-8bc350f964a4.png)
