### ISSUE TITLE
Asset Not Found Error

### ISSUE THREAD

**Issue by Exoceus** [OSSDC/OSSDC-SIM#2]
Hello, when I try to load in the F1-Tenth car, that works perfectly. However, whenever I change the name in "add_agent", I keep getting Asset Not Found for every other vehicle. For example, I tried to load the `DallaraIL15` using (I already have a local version of the vehicle saved in the data path and shows up in the data.db file:

`ego = sim.add_agent(name = "e768f24a-2d51-41b2-8976-52d2ed4178a5", agent_type = lgsvl.AgentType.EGO, state = None)`
and
`ego = sim.add_agent(name = "a7a860aa-f386-454c-a45e-ca3e8577fcc4", agent_type = lgsvl.AgentType.EGO, state = None)`

However, I got the respective Errors:

```
Traceback (most recent call last):
  File "C:\Users\User\Downloads\LGSVLLocalTesting\F1TENTH_SVL-Simulator\Python-Scripts\03_Multi_Ego.py", line 256, in <module>
    ego = sim.add_agent(name = "e768f24a-2d51-41b2-8976-52d2ed4178a5", agent_type = lgsvl.AgentType.EGO, state = None)
  File "c:\users\indyadmin\downloads\lgsvllocaltesting\pythonapi\lgsvl\utils.py", line 23, in new_f
    return f(*args, **kwargs)
  File "c:\users\indyadmin\downloads\lgsvllocaltesting\pythonapi\lgsvl\simulator.py", line 164, in add_agent
    uid = self.remote.command("simulator/add_agent", args)
  File "c:\users\indyadmin\downloads\lgsvllocaltesting\pythonapi\lgsvl\remote.py", line 69, in command
    raise Exception(data["error"])
Exception: Could not find asset with Id e768f24a-2d51-41b2-8976-52d2ed4178a5 (NotFound)
```

```
Traceback (most recent call last):
  File "C:\Users\User\Downloads\LGSVLLocalTesting\F1TENTH_SVL-Simulator\Python-Scripts\03_Multi_Ego.py", line 256, in <module>
    ego = sim.add_agent(name = "a7a860aa-f386-454c-a45e-ca3e8577fcc4", agent_type = lgsvl.AgentType.EGO, state = None)
  File "c:\users\indyadmin\downloads\lgsvllocaltesting\pythonapi\lgsvl\utils.py", line 23, in new_f
    return f(*args, **kwargs)
  File "c:\users\indyadmin\downloads\lgsvllocaltesting\pythonapi\lgsvl\simulator.py", line 164, in add_agent
    uid = self.remote.command("simulator/add_agent", args)
  File "c:\users\indyadmin\downloads\lgsvllocaltesting\pythonapi\lgsvl\remote.py", line 69, in command
    raise Exception(data["error"])
Exception: Could not find asset with Id a7a860aa-f386-454c-a45e-ca3e8577fcc4 (NotFound)
```

**Comment by Exoceus** [comment]
Also, how would I load in personal sensor configurations that are private? I have them downloaded locally, but I get asset not found error for that as well

**Comment by mslavescu** [comment]
I'll add all public resources to race.ossdc.org so you could use them from API scripts.

This demo is using the Dallara IL-15:
https://github.com/OSSDC/OSSDC-SIM-Demos/discussions/2

Try the steps from here:
https://github.com/OSSDC/OSSDC-SIM-Demos/tree/main/simulations/LVMS-Dallara-AutowareAuto-2-EGOs

Private assets need to be added manually to the data.db and to the appropriate folder.

We will improve this process in next few weeks.

**Comment by HuaweiAlgolux** [comment]
it would be great if anyone can show us how to add private assets to data.db and to the appropriate folder?

**Comment by mslavescu** [comment]
Check this comment on how to use other maps and vehicles configs:
https://github.com/OSSDC/OSSDC-SIM/issues/3#issuecomment-1166593428
