### ISSUE TITLE
Problem running the F1TENTH example

### ISSUE THREAD

**Issue by emanef13** [OSSDC/OSSDC-SIM#20]
Hi guys,

I have downloaded and run the OSSDC-SIM-v1.
However when, I run the python script Pure_Pursuit.py, from the F1Tenth-Api folder it returns the error below:

**<Set env LGSVL__SIMULATOR_HOST
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/eefthymiou/ad_sims/ossdc/PythonAPI/lgsvl/remote.py", line 29, in run
    self.loop.run_until_complete(self.process())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/eefthymiou/ad_sims/ossdc/PythonAPI/lgsvl/remote.py", line 37, in process
    self.websocket = await websockets.connect(self.endpoint, compression=None)
  File "/home/eefthymiou/venvs/py_ossdc/lib/python3.8/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
>**

Any input on how I can make it run?
Thanks!

**Comment by emanef13** [comment]
Ok, I managed to run the F1TENTH example code :) 
Here are the steps that I followed, to make it run:
1) 
The code still uses the wise module from lgsvl  in line 249 sim = lgsvl.Simulator(SIMULATOR_HOST, env.int("LGSVL__SIMULATOR_PORT", lgsvl.wise.SimulatorSettings.simulator_port))
So, I changed it to sim = lgsvl.Simulator(SIMULATOR_HOST, int(SIMULATOR_API_PORT))
and added before that SIMULATOR_API_PORT = env.str("OSSDC__SIMULATOR_API_PORT", '8181')
if SIMULATOR_API_PORT is None:
    print("Set env OSSDC__SIMULATOR_API_PORT")
    exit()

2) 
Also, I had to manually change the paths to the optimal raceline. For some reason it was not recognized when it is written as ./Spielperg_raceline.csv . 

3)
Commented out all numba-jit functions, they were giving me some errors. Everything works smooth fast even without numba.

4) 
Also, I removed the ROS_BBRIDGE connection, as of now.

Comment: Maybe we should open a pr for step (1)
